### ISSUE TITLE
fix UI: Login/SignUp page UI

### ISSUE THREAD

**Issue by rajat-mehra05** [shivanigangadharan/sanyukt#16]
Hey Shivani, your social media project is great. I have a few suggestions though for Login and Sign up page.
- The UI of those pages seems broken
- You can use border on input element while they are on focus
- Also, you can add `guest user login` so that it's easy for users to test the app quickly.

Let me know if you find these suggestions useful. :)

![image](https://user-images.githubusercontent.com/35677839/172998950-5c5e7c72-d35d-408d-9a4a-0ad52ed13bc4.png)

**Comment by shivanigangadharan** [comment]
> Hey Shivani, your social media project is great. I have a few suggestions though for Login and Sign up page.
> 
> * The UI of those pages seems broken
> * You can use border on input element while they are on focus
> * Also, you can add `guest user login` so that it's easy for users to test the app quickly.
> 
> Let me know if you find these suggestions useful. :)
> 
> ![image](https://user-images.githubusercontent.com/35677839/172998950-5c5e7c72-d35d-408d-9a4a-0ad52ed13bc4.png)

Hi @rajat-mehra05 ! Thank you for going through the app and suggesting these changes. I have fixed the UI for login and sign up page, added borders for input and have also added guest login. Let me know in case I missed something :)
PR with fixes - #15

**Comment by rajat-mehra05** [comment]
> > Hey Shivani, your social media project is great. I have a few suggestions though for Login and Sign up page.
> > 
> > * The UI of those pages seems broken
> > * You can use border on input element while they are on focus
> > * Also, you can add `guest user login` so that it's easy for users to test the app quickly.
> > 
> > Let me know if you find these suggestions useful. :)
> > ![image](https://user-images.githubusercontent.com/35677839/172998950-5c5e7c72-d35d-408d-9a4a-0ad52ed13bc4.png)
> 
> Hi @rajat-mehra05 ! Thank you for going through the app and suggesting these changes. I have fixed the UI for login and sign up page, added borders for input and have also added guest login. Let me know in case I missed something :) PR with fixes - #15

Great work. Can you try to give less padding in between those elements and make sure you don't have scroll behavior for the login and sign up page?
![image](https://user-images.githubusercontent.com/35677839/173117073-c73c4e20-e88d-4688-9dd1-7c6d817f1032.png)

![image](https://user-images.githubusercontent.com/35677839/173117150-9b40b964-4a06-4824-b7cc-450cd0024e08.png)

Try to prevent the page from scrolling behavior for these pages. :)
